"""empty message

Revision ID: ee3f8a65a820
Revises: 4a0892261df8
Create Date: 2016-12-30 21:26:59.841000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee3f8a65a820'
down_revision = '4a0892261df8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('github_url', sa.String(length=200), nullable=True))
    op.add_column('front_user', sa.Column('homepage', sa.String(length=200), nullable=True))
    op.add_column('front_user', sa.Column('telphone', sa.String(length=20), nullable=False))
    op.alter_column('front_user', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.create_unique_constraint(None, 'front_user', ['telphone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'front_user', type_='unique')
    op.alter_column('front_user', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_column('front_user', 'telphone')
    op.drop_column('front_user', 'homepage')
    op.drop_column('front_user', 'github_url')
    # ### end Alembic commands ###
